run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - misspell

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
